### PR TITLE
Converted store and discover to Docker alpine-node

### PR DESCRIPTION
**Pull request by exceptionfactory**
Converted cti-stix-store and cti-stix-discover Docker configurations to use [mhart/alpine-node](https://hub.docker.com/r/mhart/alpine-node/) as base image to reduce image sizes addressing issue #56.

### CODE REVIEW

**Comment by johnwunder** [comment]
ah I was wondering why there were two different base images. Is the plan to convert all images to use Alpine rather than Ubuntu (node:slim)?

The reason I noticed is that we use SSL inspection and I need to install our certs and proxy settings. I haven't quite figured out how to do that on Alpine but if the intent is to switch all images over I'll do so.

**Comment by exceptionfactory** [comment]
@johnwunder The goal is to reduce Docker image sizes where possible without impacting current implementations, so for cti-stix-store and cti-stix-discover, switching to alpine-node was a drop-in replacement.  However, Alpine Linux does not currently work with node-sass, which requires a platform-specific binary, so cti-stix-ui continues to use the node:slim image.

The cti-stix-gateway container configuration uses the base Nginx image, so it should work with standard certificates.  If the current Docker Compose configuration is presenting problems in your environment, feel free to submit an issue so we can track down potential improvements.

**Comment by johnwunder** [comment]
I see, that makes sense. It sounds like the goal would be for everything to be on Alpine Linux so I'll figure out the SSL issues there.

The configuration unfortunately is environment-specific so it'll never work out of the box.

**Comment by infosec-alchemist** [comment]
Which configuration is environment specific?

**Pull request merged**
